export const SHOW_FILTERS_PANEL = 'SHOW_FILTERS_PANEL';
export const HIDE_FILTERS_PANEL = 'HIDE_FILTERS_PANEL';

export const SHOW_SIDE_DRAWER = 'SHOW_SIDE_DRAWER';
export const HIDE_SIDE_DRAWER = 'HIDE_SIDE_DRAWER';

export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';

export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const CLICK_ADD_REVIEW_AFTER_RATING = 'ADD_REVIEW_AFTER_RATING';
export const SHOW_ADD_REVIEW = 'SHOW_ADD_REVIEW';
export const HIDE_ADD_REVIEW = 'HIDE_ADD_REVIEW';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';

export const SET_LOADING = 'SET_LOADING';

export const SET_IS_USING_EMAIL_AUTH = 'SET_IS_USING_EMAIL_AUTH';
export const SET_IS_USING_EMAIL_AUTH_ROUTE = 'SET_IS_USING_EMAIL_AUTH_ROUTE';

export const SORT_RESULTS_BY = 'SORT_RESULTS_BY';
export const ORDER_RESULTS_BY = 'ORDER_RESULTS_BY';

export const SET_REVIEWS = 'SET_REVIEWS';
export const UPDATE_REVIEWS = 'UPDATE_REVIEWS';
export const SET_OFFSET = 'SET_OFFSET';
export const INCREASE_OFFSET = 'INCREASE_OFFSET';

export const SET_STORES = 'SET_STORES';
export const UPDATE_STORES = 'UPDATE_STORES';
export const SET_SELECTED_STORE = 'SET_SELECTED_STORE';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
