export const SHOW_FILTERS_PANEL = 'SHOW_FILTERS_PANEL';
export const HIDE_FILTERS_PANEL = 'HIDE_FILTERS_PANEL';

export const SHOW_SIDE_DRAWER = 'SHOW_SIDE_DRAWER';
export const HIDE_SIDE_DRAWER = 'HIDE_SIDE_DRAWER';

export const TOGGLE_PRODUCT_MODAL = 'TOGGLE_PRODUCT_MODAL';
export const TOGGLE_ADD_PRODUCTS_MODAL = 'TOGGLE_ADD_PRODUCTS_MODAL';
export const TOGGLE_ADVERTISE_MODAL = 'TOGGLE_ADVERTISE_MODAL';
export const TOGGLE_TERMS_MODAL = 'TOGGLE_TERMS_MODAL';
export const TOGGLE_PRIVACY_MODAL = 'TOGGLE_PRIVACY_MODAL';
