export const SHOW_FILTERS_PANEL = 'SHOW_FILTERS_PANEL';
export const HIDE_FILTERS_PANEL = 'HIDE_FILTERS_PANEL';

export const SHOW_PRODUCT_MODAL = 'SHOW_PRODUCT_MODAL';
export const HIDE_PRODUCT_MODAL = 'HIDE_PRODUCT_MODAL';
